name: Build
steps:
  - name: create aosp directory
    cmd: mkdir aosp
  - name: download aosp
    workdir: aosp
    cmd: repo init --partial-clone -b main -u https://android.googlesource.com/platform/manifest
  - name: create local manifests directory
    workdir: aosp/.repo
    cmd: mkdir local_manifests
  - name: generate manifests
    workdir: .
    cmd: uv run python generate_manifests.py "./aosp/.repo/local_manifests"
  - name: sync repo
    workdir: aosp
    cmd: repo sync -c -j32
